### ISSUE TITLE
bug: Document command returns malformed comments

### ISSUE THREAD

**Issue by kukicado** [sourcegraph/cody#2058]
### Version

v0.17.1701443218

### Describe the bug

Running the Document command in a .php file returns malformed text. It appears that some of the comments are returned twice, but only some are properly formatted. 

![screenshot_2023-12-01_at_3 05 47___pm_720](https://github.com/sourcegraph/cody/assets/1770570/21147be0-e3dd-4d75-af88-f056b13604ec)

### Expected behavior

It should return a doctoring without additional copy that breaks the UI.

### Additional context

I tried the Doc command in a couple different .php files in a large Laravel based project. This behavior did not happen in every file, but on the ones it did, it did so consistently, I was not able to ever generate a clean docstring for this function using the Document command.

**Comment by abeatrix** [comment]
i've run into this issue before and I believe this has been fixed by @umpox in https://github.com/sourcegraph/cody/pull/1883#pullrequestreview-1757511751

**Comment by taylorsperry** [comment]
I think this still isn't working quite right. [Loom](https://www.loom.com/share/ef8aedb7fbe248feb0c5e5add71af886). I'm on v0.18 and it still looks like documentation for php is malformatted, and "Undo" doesn't fully undo the generated code.

**Comment by beyang** [comment]
I suspect this is happening, because VS Code auto-injects doc delimiters like `*/` when you start a doc block
