### ISSUE TITLE
bug: UNABLE TO SEND MESSAGE You've used all chat messages and commands for today. Learn More 

### ISSUE THREAD

**Issue by ALAXAY** [sourcegraph/cody#4515]
### Version

Cody: AI Coding Assistant with Autocomplete & Chat v1.21.1717993747 

### Describe the bug

I AM A PRO VERSION USER, AFTER 10 MESSAGES IN CODY CHAT, I GET A MESSAGE UNABLE TO SEND MESSAGE You've used all chat messages and commands for today. Learn More........

### Expected behavior

restoring chat function

**Comment by kalanchan** [comment]
hey @ALAXAY sorry about this, this is a bug on our end and we're working to resolve it as quickly as we can. 

Could you share your username or email and we'll have someone reach out? 

Thanks!

**Comment by ALAXAY** [comment]
rocimwan123@gmail.com

**Comment by ALAXAY** [comment]
rocimean123@gmail.com

**Comment by ALAXAY** [comment]
cody chat still doesn't work

**Comment by ALAXAY** [comment]
cody chat still doesn't work

**Comment by ALAXAY** [comment]
cody chat still doesn't work

**Comment by ALAXAY** [comment]
cody chat still doesn't work   ??????????????????????????????????????????????????????????????????????   UNABLE TO SEND MESSAGE
You've used all chat messages and commands for today.


Learn More
Usage will reset today at 7:42 PM

Try again with different context
Public knowledge only
Add context...

**Comment by ALAXAY** [comment]
![_22](https://github.com/sourcegraph/cody/assets/34536179/c6c48719-af35-413e-b640-2b7fed1d60af)

**Comment by nn1k4** [comment]
![screen](https://github.com/sourcegraph/cody/assets/39860945/3ba76f55-0121-4b93-8ada-d106559f2ec3)

**Comment by ALAXAY** [comment]
Cody also doesn't work in Visual Studio with code completion
![cody_bug](https://github.com/sourcegraph/cody/assets/34536179/5c4b404b-8ec3-4f8f-af9e-23ac95e23eec)

**Comment by ALAXAY** [comment]
Please tell me and answer, cody has not been working for three days now, I really liked the development of your chat functions, but unfortunately this function is not working yet. Should I expect a recovery or perhaps there was a collapse on your server? Give me feedback so that I understand how to continue paying for using your service?

**Comment by kalanchan** [comment]
hey @ALAXAY thank you for your patience. We should have fixed it on the backend, can you logout and log back in and see if the issue has been resolved?

**Comment by ALAXAY** [comment]
Hi Kalan,

Thanks for the quick fix. It's already working properly.

Thanks,
AleX

**Comment by ALAXAY** [comment]
again same problem not working CODY!!! error: UNABLE TO SEND MESSAGE
You’ve used all chat messages and commands for today. my name is ALAXAY

**Comment by ALAXAY** [comment]
again same problem not working CODY!!! error: UNABLE TO SEND MESSAGE
You’ve used all chat messages and commands for today. my name is ALAXAY

**Comment by ALAXAY** [comment]
Now the Cody chat is not responding at all, I'm trying to fulfill the request (((

**Comment by ALAXAY** [comment]
HELP!!!!!

**Comment by ALAXAY** [comment]
Hi Kalan,

I'm writing to you again regarding the same issue with CODY. I logged out
and logged back in, but the problem persists. I'm still getting the error
message "UNABLE TO SEND MESSAGE. You've used all chat messages and commands
for today."

I'm not sure what's causing this issue, but it's very frustrating. I rely
on CODY for my work, and I need to be able to send messages and commands.

Please let me know if there's anything else I can do to fix this issue.

Thanks,
AleX

**Comment by kalanchan** [comment]
@nn1k4 Could you also provide your email and username and i'll look into this as well?

**Comment by ALAXAY** [comment]
rocimean123@gmail.com.          Alaxay

**Comment by kalanchan** [comment]
@ALAXAY I see that you closed the ticket, is your issue resolved now?

**Comment by ALAXAY** [comment]
no, unfortunately not solved, this morning it worked, I was glad, but after lunch and now the same error is happening again

**Comment by ALAXAY** [comment]
Help please!!!!!!!

**Comment by ALAXAY** [comment]
please help me solve the problem with the cody error, I can’t reach you my
name is ALAXAY

чт, 13 июн. 2024 г., 08:41 AleX Fesenko ***@***.***>:

> Hi Kalan,
>
> Thanks for the quick fix. It's already working properly.
>
> Thanks,
> AleX
>
>

**Comment by ALAXAY** [comment]
I'm getting an error message that says "UNABLE TO SEND MESSAGE." Сody has not worked for more than 6 days

**Comment by ALAXAY** [comment]
I'm getting an error message that says "UNABLE TO SEND MESSAGE." Сody has not worked for more than 6 days

**Comment by MrTino** [comment]
UNABLE TO SEND MESSAGE
You've used all of your chat messages and commands for today.

Cody AI, I can not chat

**Comment by MrTino** [comment]
![Screenshot 2024-09-20 102716](https://github.com/user-attachments/assets/7328a001-0ecf-45af-a7e5-a22d0029ae27)

Please help me

**Comment by OrganicChem** [comment]
![Screenshot 2024-11-27 at 8 43 10 AM](https://github.com/user-attachments/assets/28e142e8-bb4c-457f-8649-d662a06a2303)

**Comment by imposhster** [comment]
As a pro user, I just ran into this today...was not expecting this to happen as nothing i was doing was abusive merely conversational. 

![Image](https://github.com/user-attachments/assets/610bfab3-69f3-4541-99be-fe441cbe11bc)

**Comment by chrisanderton** [comment]
Same, used it sporadically for a couple of hours this morning, came back this evening and got this message. Could be a backend issue, or perhaps a sign of them cutting back on what "unlimited" means.
