### ISSUE TITLE
Cody CLI - Noxide Loader Error: Cannot Find Module './noxide.darwin-arm64-6MFXXAGT.node

### ISSUE THREAD

**Issue by dvcrn** [sourcegraph/cody#7378]
## Environment Information
- **Cody Version**: 5.5.6
- **Node.js Version**: 23.9.0 (installed via `fnm`)
- **OS**: macOS 15.3.1

## Steps to Reproduce
1. Install `@sourcegraph/cody` globally using `npm install -g @sourcegraph/cody`.
2. Attempt to run a Cody-related command (e.g., `cody chat`)
3. Encounter the error below.

## Expected Behavior
The `@sourcegraph/cody` package should load successfully, including all required native modules like `noxide.darwin-arm64-6MFXXAGT.node`, and execute the intended functionality (e.g., chat or extension activation).

## Actual Behavior
The Noxide Loader fails to load the native module, resulting in the following error:

```
🤜　　　　🤛  Noxide Loader: Loading noxide library
Noxide Loader: Could not load noxide library Error: Cannot find module './noxide.darwin-arm64-6MFXXAGT.node'
Require stack:
- /Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at importLib (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:357633:18)
    at Object.load2 (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:357610:10)
    at loadNoxideLib (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:357692:18)
    at activate (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:303205:49)
    at activate2 (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:357675:10)
    at initializeVscodeExtension (/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:148111:9)
    at /Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js:148378:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist/index.js'
  ]
}
DelegatingProxy: No CA certs loaded from noxide. Falling back to legacy defaults
✖ No message provided. To send a message, use the --message option or pipe a message to stdin via --stdin
```

### Debug Output
With `NODE_DEBUG=module`:
```
MODULE 27216: load built-in module tls
🤜　　　　🤛  Noxide Loader: Loading noxide library
MODULE 27216: Module._load REQUEST ./noxide.darwin-arm64-6MFXXAGT.node parent: .
MODULE 27216: RELATIVE: requested: ./noxide.darwin-arm64-6MFXXAGT.node from parent.id .
MODULE 27216: looking for ["/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist"]
Noxide Loader: Could not load noxide library Error: Cannot find module './noxide.darwin-arm64-6MFXXAGT.node'
```

### Directory Contents
The `dist` directory lacks any `noxide` files:
```
/Users/david/.local/share/fnm/node-versions/v23.9.0/installation/lib/node_modules/@sourcegraph/cody/dist:
canvaskit.wasm  index.js*  index.js.map  tree-sitter-bash.wasm  tree-sitter-c.wasm  tree-sitter-c_sharp.wasm  tree-sitter-cpp.wasm  tree-sitter-css.wasm  tree-sitter-dart.wasm  tree-sitter-elisp.wasm  tree-sitter-elixir.wasm  tree-sitter-elm.wasm  tree-sitter-go.wasm  tree-sitter-html.wasm  tree-sitter-java.wasm  tree-sitter-javascript.wasm  tree-sitter-json.wasm  tree-sitter-kotlin.wasm  tree-sitter-lua.wasm  tree-sitter-objc.wasm  tree-sitter-ocaml.wasm  tree-sitter-php.wasm  tree-sitter-python.wasm  tree-sitter-rescript.wasm  tree-sitter-ruby.wasm  tree-sitter-rust.wasm  tree-sitter-scala.wasm  tree-sitter-swift.wasm  tree-sitter-tsx.wasm  tree-sitter-typescript.wasm  tree-sitter.wasm  webviews/  win-ca-roots.exe
```

## Troubleshooting Attempted
1. **Reinstalled `@sourcegraph/cody`**:
   ```bash
   npm uninstall -g @sourcegraph/cody
   npm install -g @sourcegraph/cody
   ```
   - No `noxide` file appeared in `dist`.

2. **Upgrading/downgrading node**
- 
- Tried v20 lts and latest

**Comment by umpox** [comment]
Thank you for reporting! This should be fixed in the latest version (5.5.17): https://www.npmjs.com/package/@sourcegraph/cody/v/5.5.17

**Comment by jonathan-rst** [comment]
> Thank you for reporting! This should be fixed in the latest version (5.5.17): https://www.npmjs.com/package/@sourcegraph/cody/v/5.5.17

I can confirm that this is still an issue on 5.5.17, except the error trace is slightly different: 

`🤜　　　　🤛  Noxide Loader: Loading noxide library
DelegatingProxy: Loaded 190 CA certs from noxide
　🤜✨🤛　　  Initializing...Uncaught exception: AbortError2: The user aborted a request.
    at abort3 (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:47863:23)
    at AbortSignal.abortAndFinalize2 (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:47877:11)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:762:26)
    at runAbort (node:internal/abort_controller:447:10)
    at abortSignal (node:internal/abort_controller:433:3)
    at AbortController.abort (node:internal/abort_controller:466:5)
    at AbortSignal.abortHandler (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:51788:19)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:762:26)
    at runAbort (node:internal/abort_controller:447:10)
    at abortSignal (node:internal/abort_controller:433:3)
    at AbortController.abort (node:internal/abort_controller:466:5)
    at AbortAggregator.abort (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53628:25)
    at GraphQLResultCache.invalidate (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53704:22)
    at Object.next (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53645:21) {
  type: 'aborted'
}
Uncaught exception: AbortError2: The user aborted a request.
    at abort3 (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:47863:23)
    at AbortSignal.abortAndFinalize2 (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:47877:11)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:762:26)
    at runAbort (node:internal/abort_controller:447:10)
    at abortSignal (node:internal/abort_controller:433:3)
    at AbortController.abort (node:internal/abort_controller:466:5)
    at AbortSignal.abortHandler (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:51788:19)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:762:26)
    at runAbort (node:internal/abort_controller:447:10)
    at abortSignal (node:internal/abort_controller:433:3)
    at AbortController.abort (node:internal/abort_controller:466:5)
    at AbortAggregator.abort (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53628:25)
    at GraphQLResultCache.invalidate (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53704:22)
    at Object.next (/Users/jthomas/.nvm/versions/node/v22.14.0/lib/node_modules/@sourcegraph/cody/dist/index.js:53645:21) {
  type: 'aborted'
}
`

**Comment by PriNova** [comment]
Hey @dvcrn 

It seems that this is a different issue. Please open a new issue report so that we can handle it properly.

Thank you
